Add support for riscv64
fwupd/fwupd-efi pull request #41
Opened 2023-03-03 14:24 UTC by hughsie

2023-03-03 14:35 UTC, superm1 reviewed
There's more to it than this.  Take a look at all the stuff that was being done on the linked branch on
https://github.com/fwupd/fwupd-efi/issues/19

2023-03-03 14:35 UTC, superm1 commented
CC @xypron

2023-03-03 14:36 UTC, superm1 commented
And I think we need at least a cross compile CI job for some OS.

2023-03-03 14:41 UTC, hughsie commented
Ohh I was just proxying a downstream patch. Input from @xypron certainly very welcome.

2023-04-23 10:50 UTC, CoelacanthusHex reviewed
I tested it in Arch RISC-V package. It works well.

2023-04-23 10:50 UTC, CoelacanthusHex commented on efi/meson.build
>  # older objcopy for Aarch64 and ARM32 are not EFI capable.
```suggestion
# older objcopy for Aarch64, ARM32 and riscv are not EFI capable.
```
Modify comment at same time.

2023-04-23 11:17 UTC, xypron commented
Am 23. April 2023 12:50:27 MESZ schrieb Coelacanthus ***@***.***>:
>@CoelacanthusHex commented on this pull request.
>
>I tested it in Arch RISC-V package. It works well.
>
>> @@ -93,7 +93,7 @@ endif
> 
> # older objcopy for Aarch64 and ARM32 are not EFI capable.
>
>```suggestion
># older objcopy for Aarch64, ARM32 and riscv are not EFI capable.

%s/riscv/RISC-V/

>```
>Modify comment at same time.
>

2023-04-23 11:35 UTC, CoelacanthusHex commented
> Am 23. April 2023 12:50:27 MESZ schrieb Coelacanthus ***@***.***>:
> @CoelacanthusHex commented on this pull request. I tested it in Arch RISC-V package. It works well. > @@ -93,7 +93,7 @@ endif # older objcopy for Aarch64 and ARM32 are not EFI capable. ```suggestion # older objcopy for Aarch64, ARM32 and riscv are not EFI capable.
> %s/riscv/RISC-V/
> […](#)
> ``` Modify comment at same time.

Updated. Thanks.

2023-07-04 13:07 UTC, gmbr3 requested changes
✓ Builds correctly on openSUSE riscv64
⚠ No riscv64 crt0/lds (SBAT patched) in-tree, useful for people that don't patch gnu-efi

2024-02-18 21:16 UTC, closed without merging